### ISSUE TITLE
当日のシフトが決まっている

### ISSUE THREAD

**Issue by futabooo** [eureka-twelve/techbookfest4#20]
# 概要
4/22のシフトを決める
- ブース準備
- ブースでの売り子
- ブース片付け

タイムスケジュール
- 10時〜 出展者入場開始
    - 頒布物の確認、見本誌の提出
- 11時〜 一般参加入場
- 17時 終了
- 17~18時 出展者撤収

## シフト
ならべく僕はいるようにしようと思ってますがスペースの都合によっては上の階にあるカフェで監視してますｗ

時間 | メンバー | やること
-- | -- | --
10-12 | yuyakaido, satoshin21, lemon (futabooo) | ブースの準備、売り子
12-14 | yutaro6547, boxp (futabooo)  | 売り子
14-16 | yu81, haru2036 (futabooo)  | 売り子
16-18 | futabooo, takochuu | ブース片付け、売り子

# DONEの条件
- [ ] シフト表ができてる

**Comment by yuyakaido** [comment]
当日は終日空けてあるので、基本的にはいつでもシフト入れます！

**Comment by 13m00n** [comment]
自分15時以降が空いてます。13時ごろに京都の知り合いがランチしたいとの話ででなきゃいけないのです。

**Comment by suzukiyut27** [comment]
僕はその日は空けているので、どこでもシフト入れます！

**Comment by boxp** [comment]
同じくどこでも大丈夫そうです！ :ok_woman:

**Comment by satoshin21** [comment]
いつでもシフト入れやす

**Comment by yu81** [comment]
昼頃以降(12時以降)OKです！

**Comment by haru2036** [comment]
ぼくも12時以降参加できます！

**Comment by futabooo** [comment]
決まった。カレンダーに転載しといた
