### ISSUE TITLE
当日必要なこと・もの

### ISSUE THREAD

**Issue by futabooo** [eureka-twelve/techbookfest4#21]
# 概要
当日ブースで必要な道具や、必要なことをまとめる

## 必要なもの
- [x] 筆記用具
- [x] テーブルクロス
- [x] ブックスタンド
- [x] 値札
- [x] コインケース（100円玉、500円玉）
- [ ] お釣り用の小銭（電子決済用意するけど、念のためあったほうがよさそう）
- [x] 公式後払い決済用のQRコード印刷しておく

## 決済
800¥！
~- [x] 本をいくらにするか~
- 技術書典が提供してくれている決済システムをつかう(今回はAndroidとios両方提供される）
https://blog.techbookfest.org/2017/10/18/payment/
https://blog.techbookfest.org/2018/04/15/payment-ios/
- 念のため現金も対応できるようにしておく

# DONEの条件
- [ ] まとまったら

**Comment by futabooo** [comment]
OnePay使うのがよさそうか？手数料かかるけど払う側はカードだけあればいい

**Comment by satoshin21** [comment]
ブックスタンド候補 安い(492円)
https://www.amazon.co.jp/%E3%82%A2%E3%82%B9%E3%82%AB-%E3%83%96%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89-%E3%83%95%E3%83%AA%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89-%E3%82%B7%E3%83%AB%E3%83%90%E3%83%BC-DB523/dp/B019ME13LO/ref=sr_1_12?ie=UTF8&qid=1523938686&sr=8-12&keywords=%E3%83%96%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89

**Comment by satoshin21** [comment]
あった方がよいかもしれないもの
* コインケース (両替の時、まごつかないように)
* 値札
* エウレカシール

**Comment by 13m00n** [comment]
コースターはどうですか？

**Comment by futabooo** [comment]
さとしんさんが書いてくれたやつだいたい買った。明日か明後日会社に届く。
ブックスタンド
コインケース
値札
